import { defineConfig } from 'vite';
import react from '@vitejs/plugin-react';
import { resolve } from 'path';

// Determine if we're in development or production
const isDev = process.env.NODE_ENV === 'development' || !process.env.NODE_ENV;
const dfxNetwork = process.env.DFX_NETWORK || (isDev ? 'local' : 'ic');

export default defineConfig({
  plugins: [react()],
  assetsInclude: ['**/*.GIF', '**/*.PNG', '**/*.JPG', '**/*.JPEG'],
  define: {
    global: 'globalThis',
    'process.env.DFX_NETWORK': JSON.stringify(dfxNetwork),
    'process.env.NODE_ENV': JSON.stringify(process.env.NODE_ENV || (isDev ? 'development' : 'production')),
  },
  resolve: {
    alias: {
      '@': resolve(__dirname, 'src'),
      '@components': resolve(__dirname, 'src/components'),
      '@pages': resolve(__dirname, 'src/pages'),
      '@services': resolve(__dirname, 'src/services'),
      '@stores': resolve(__dirname, 'src/stores'),
      '@utils': resolve(__dirname, 'src/utils'),
      '@types': resolve(__dirname, 'src/types'),
      // Alias for canister declarations (generated by dfx generate)
      '@declarations': resolve(__dirname, 'src/declarations'),
    },
  },
  server: {
    port: 5173,
    host: true, // Allow external connections
    proxy: {
      // Proxy API calls to local dfx replica
      '/api': {
        target: 'http://127.0.0.1:4943',
        changeOrigin: true,
        rewrite: (path) => path.replace(/^\/api/, ''),
      },
      // Proxy IC canister calls
      '/canister': {
        target: 'http://127.0.0.1:4943',
        changeOrigin: true,
      },
    },
  },
  build: {
    outDir: 'dist',
    sourcemap: isDev, // Enable sourcemaps in development
    minify: isDev ? false : 'terser', // Only minify in production
    rollupOptions: {
      output: {
        manualChunks: {
          vendor: ['react', 'react-dom', 'react-router-dom'],
          dfinity: ['@dfinity/agent', '@dfinity/auth-client', '@dfinity/principal', '@dfinity/candid'],
          ui: ['framer-motion', 'lucide-react'],
        },
      },
    },
    // Optimize for ICP deployment
    chunkSizeWarningLimit: 1000,
  },
  // Optimize dependencies
  optimizeDeps: {
    include: [
      'react',
      'react-dom',
      'react-router-dom',
      '@dfinity/agent',
      '@dfinity/auth-client',
      '@dfinity/principal',
      '@dfinity/candid',
    ],
  },
});


